kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-allow-httpservice
  namespace: server-netpol
spec:
  podSelector:
    matchLabels:
      service: http
  ingress:
    - ports:
        - port: 8080
      from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: client-netpol
          podSelector:
            matchLabels:
              service: client
