apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: demo-policy-access-frontend
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 8080
        - port: 443
      from:
       - podSelector: {}

---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-allow-client-to-access-postgresql
spec:
  podSelector:
    matchLabels:
      app: postgres
  ingress:
    - ports:
        - port: 5432
      from:
        - podSelector:
            matchLabels:
              app: client
