apiVersion: v1
kind: Pod
metadata:
  labels:
    run: apache
  name: apache
spec:
  containers:
  - image: registry.access.redhat.com/rhscl/httpd-24-rhel7
    name: apache
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
