apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sleeper
  name: sleeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleeper
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sleeper
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - sleep 3600
        image: busybox
        name: busybox
        resources: {}
