apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  strategy: {}
  template:
    metadata:
      labels:
        app: apache
    spec:
      volumes:
       - name: trusted-ca
         configMap:
            name: inject-ca-bundle
            items:
             - key: ca-bundle.crt 
               path: tls-ca-bundle.pem
      containers:
      - image: registry.access.redhat.com/rhscl/httpd-24-rhel7:latest
        name: httpd-24-rhel7
        volumeMounts:
        - name: trusted-ca
          mountPath: /etc/pki/ca-trust/extracted/pem
          readOnly: true
